CMakeLists.txt: use pkg-config for libandroid-properties and android-headers
* libandroid-properties provides the library as well as properties.h
  used in:
  property_service.c:#include <hybris/properties/properties.h>
  and with newer libhybris, after this commit:
    commit 35976c201741cfc21c114615b8524db5367e034a
    Author: Franz-Josef Haider <franz.haider@jolla.com>
    Date:   Thu May 17 11:42:35 2018 +0000

      hybris: properties: use system properties from bionic without hooks for android 8 and higher for simplicity

  it also needs android-properties.h provided by android-headers and for
  that we need pkg-config, because android-properties.h aren't in
  already searched ${includedir}, but in ${includedir}/android:
  tmp-glibc/sstate-control/manifest-tissot-android-headers-halium.populate_sysroot:/OE/build/luneos-master/webos-ports/tmp-glibc/sysroots-components/tissot/android-headers-halium/usr/include/android/android-config.h
  tmp-glibc/sstate-control/manifest-hammerhead-android-headers-halium.populate_sysroot:/OE/build/luneos-master/webos-ports/tmp-glibc/sysroots-components/hammerhead/android-headers-halium/usr/include/android/android-config.h

* fixes:
    | In file included from /OE/build/luneos-warrior/webos-ports/tmp-glibc/work/tissot-webos-linux/mtp-server/0.0.3+gitrAUTOINC+6159f1a143-r0/git/src/MtpServer.cpp:44:0:
    | /OE/build/luneos-warrior/webos-ports/tmp-glibc/work/tissot-webos-linux/mtp-server/0.0.3+gitrAUTOINC+6159f1a143-r0/recipe-sysroot/usr/include/hybris/properties/properties.h:28:10: fatal error: android-config.h: No such file or directory
    |  #include <android-config.h>
    |           ^~~~~~~~~~~~~~~~~~
    | compilation terminated.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>